const state={events:window.HER_MATCH_EVENTS||[],league:"All",query:"",limit:10,selected:new Set()};
const $=id=>document.getElementById(id);
const clean=s=>s.replace(/^⚽️?\s*/,"");
const escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[char]);
const leagues=[...new Set(state.events.map(e=>e.competition))];
const shortLeague=name=>name.includes("National")?"NWSL":name.includes("Northern")?"NSL":name.includes("Super League")?"WSL":name;
function visible(){return state.events.filter(e=>(state.league==="All"||e.competition===state.league)&&`${e.title} ${e.competition}`.toLowerCase().includes(state.query.toLowerCase()));}
function renderFilters(){$("leagueFilters").innerHTML=["All",...leagues].map(l=>`<button class="filter ${state.league===l?"active":""}" data-league="${escapeHtml(l)}">${escapeHtml(l==="All"?"All leagues":shortLeague(l))}</button>`).join("");document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{state.league=b.dataset.league;state.limit=10;render();});}
function render(){renderFilters();const events=visible(),shown=events.slice(0,state.limit);$("resultCount").textContent=`${events.length} upcoming match${events.length===1?"":"es"}`;$("eventList").innerHTML=shown.length?shown.map(e=>{const d=new Date(e.start);return `<article class="event"><div class="date-block"><strong>${d.toLocaleDateString(undefined,{day:"2-digit"})}</strong><span>${d.toLocaleDateString(undefined,{month:"short",weekday:"short"})}</span></div><div><h3>${escapeHtml(clean(e.title))}</h3><span class="event-time">${d.toLocaleTimeString(undefined,{hour:"numeric",minute:"2-digit"})}</span></div><p class="event-location">${escapeHtml(e.location||"Location to be announced")}</p><span class="league-label">${escapeHtml(shortLeague(e.competition))}</span><input class="select-event" type="checkbox" aria-label="Select ${escapeHtml(clean(e.title))}" data-id="${escapeHtml(e.id)}" ${state.selected.has(e.id)?"checked":""}></article>`}).join(""):'<div class="empty">No matches found. Try a different search or league.</div>';$(`loadMore`).style.display=events.length>state.limit?"block":"none";document.querySelectorAll(".select-event").forEach(c=>c.onchange=()=>c.checked?state.selected.add(c.dataset.id):state.selected.delete(c.dataset.id));}
function escapeIcs(value=""){return value.replace(/\r/g,"").replace(/\\/g,"\\\\").replace(/,/g,"\\,").replace(/;/g,"\\;").replace(/\n/g,"\\n")}
function icsDate(value){return new Date(value).toISOString().replace(/[-:]/g,"").replace(/\.\d{3}/,"")}
function download(){let chosen=state.selected.size?state.events.filter(e=>state.selected.has(e.id)):visible();if(!chosen.length)return;const body=chosen.map(e=>`BEGIN:VEVENT\r\nUID:${e.id}@hermatch.ca\r\nDTSTAMP:${icsDate(new Date())}\r\nDTSTART:${icsDate(e.start)}\r\nDTEND:${icsDate(e.end)}\r\nSUMMARY:${escapeIcs(clean(e.title))}\r\nLOCATION:${escapeIcs(e.location)}\r\nDESCRIPTION:${escapeIcs(e.competition)}\r\nEND:VEVENT`).join("\r\n");const blob=new Blob([`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Her Match//Calendar//EN\r\nCALSCALE:GREGORIAN\r\n${body}\r\nEND:VCALENDAR\r\n`],{type:"text/calendar"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="her-match-calendar.ics";a.click();URL.revokeObjectURL(a.href)}
function renderLeagues(){$("leagueGrid").innerHTML=leagues.map(l=>{const count=state.events.filter(e=>e.competition===l).length;return `<article class="league-card"><b>${escapeHtml(shortLeague(l))}</b><div><h3>${escapeHtml(l)}</h3><p>${count} upcoming matches</p></div></article>`}).join("")+`<article class="league-card"><b>+</b><div><h3>More coming soon</h3><p>Basketball, hockey, tennis, and more.</p></div></article>`}
$("search").oninput=e=>{state.query=e.target.value;state.limit=10;render()};$("clearFilters").onclick=()=>{state.league="All";state.query="";$("search").value="";render()};$("loadMore").onclick=()=>{state.limit+=10;render()};$("downloadCalendar").onclick=download;render();renderLeagues();
